<template>
  <div id="pubnubchat">
    <chat-container/>
  </div>
</template>

<script>
import ChatContainer from '../components/pubnubchat/ChatContainer'
import DefaultChats from '../plugins/pubnubchat/default-chats'
import botInit from '../plugins/pubnubchat/bot'
import util from '../plugins/pubnubchat/util'

export default {
  components: {
    ChatContainer,
  },
  // created () {
  //   console.log('Chat-engine created')
  //   const ChatEngine = this.$chatEngine
  //   const store = this.$store

  //   ChatEngine.connect(me.uuid, me)

  //   document.addEventListener('beforeunload', function () {
  //     ChatEngine.disconnect()
  //   })

  //   ChatEngine.on('$.ready', function (data) {
  //     // store my new user as `me`
  //     let me = data.me
  //     store.commit('chat/setMe', {
  //       me
  //     })

  //     // Auto add a 1:1 chat to UI when invited
  //     // more invite code in (components/FriendList.vue)
  //     me.direct.on('$.invite', (event) => {
  //       let uuids = [event.sender.uuid, store.state.me.uuid].sort()
  //       let chatKey = uuids.join('-')

  //       // Don't make the same 1:1 chat if it already exists
  //       if (store.state.chats[chatKey]) {
  //         return
  //       }

  //       // Make the new 1:1 private Chat
  //       util.newChatEngineChat(
  //         store,
  //         ChatEngine, {
  //           chatKey,
  //           uuid: event.sender.uuid,
  //         },
  //         true,
  //       )
  //     })

  //     ChatEngine.global.key = globalChatSettings.chatKey

  //     // Make a Global Chat and add to the client's UI
  //     const globalChat = util.newChatEngineChat(
  //       store,
  //       ChatEngine,
  //       globalChatSettings,
  //     )

  //     // Get the message history in the global chat
  //     globalChat.search({
  //       event: 'message',
  //       limit: 6,
  //     })

  //     store.commit('chat/setCurrentChat', {
  //       chatKey: globalChat.key,
  //     })

  //     // Create a new chat for each user in the friends list
  //     DefaultChats.friends.forEach(function (friend) {
  //       console.log(friend)
  //       const uuids = [friend.uuid, store.state.me.uuid].sort()
  //       const chatKey = uuids.join('-')

  //       // Don't make a duplicate chat if it already exists
  //       if (
  //         store.state.chats[chatKey] ||
  //         friend.uuid === 'global'
  //       ) {
  //         return
  //       }

  //       // Make a private chat key with the Stephen bot
  //       if (friend.isChatBot) {
  //         // Init ChatBot with its own ChatEngine client (bot.js)
  //         botInit(ChatEngine, friend, chatBotURL)
  //       }

  //       // Add the chat key to the Chat object for Vue UI use
  //       friend.chatKey = chatKey

  //       // Make the new 1:1 private Chat
  //       const myChat = util.newChatEngineChat(
  //         store,
  //         ChatEngine,
  //         friend,
  //         true,
  //       )

  //       // when a user comes online
  //       myChat.on('$.online.*', (data) => {
  //         // console.log('New user', data.user.uuid);
  //       })

  //       // when a user goes offline
  //       myChat.on('$.offline.*', (data) => {
  //         // console.log('User left', data.user.uuid);
  //       })
  //     })
  //   })
  // }
}
</script>

<style>
body {
  background-image: url('../assets/pubnub-filter-blocks-bg.png');
}

#app {
  font-family: Helvetica;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #454d54;
  margin-top: 60px;
}

/* Loading Ripple Animation */
/* Generated by loading.io */
@keyframes lds-ripple {
  0% {
    top: 96px;
    left: 96px;
    width: 0;
    height: 0;
    opacity: 1;
  }
  100% {
    top: 8px;
    left: 8px;
    width: 176px;
    height: 176px;
    opacity: 0;
  }
}
@-webkit-keyframes lds-ripple {
  0% {
    top: 96px;
    left: 96px;
    width: 0;
    height: 0;
    opacity: 1;
  }
  100% {
    top: 8px;
    left: 8px;
    width: 176px;
    height: 176px;
    opacity: 0;
  }
}
.lds-ripple {
  position: relative;
}
.lds-ripple div {
  box-sizing: content-box;
  position: absolute;
  border-width: 4px;
  border-style: solid;
  opacity: 1;
  border-radius: 50%;
  -webkit-animation: lds-ripple 2.6s cubic-bezier(0, 0.2, 0.8, 1) infinite;
  animation: lds-ripple 2.6s cubic-bezier(0, 0.2, 0.8, 1) infinite;
}
.lds-ripple div:nth-child(1) {
  border-color: #000000;
}
.lds-ripple div:nth-child(2) {
  border-color: rgba(0%,0%,0%,0.675);
  -webkit-animation-delay: -1.3s;
  animation-delay: -1.3s;
}
.lds-ripple {
  width: 36px !important;
  height: 36px !important;
  -webkit-transform: translate(-18px, -18px) scale(0.18) translate(18px, 18px);
  transform: translate(-18px, -18px) scale(0.18) translate(18px, 18px);
}
</style>
